version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: frontend # specify the directory of the Dockerfile
  ports:
  - "4200:4200" # specify port mapping
 
 express: # name of the second service
  build: backend # specify the directory of the Dockerfile
  ports:
  - "3000:3000" #specify ports mapping
  links:
  - database # link this service to the database service
 
 database: # name of the third service
  image: mongo # specify image to build container from
  container_name: my-mongo-container
  environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass
            - MONGO_INITDB_DATABASE=db
  restart: always
  volumes:
  - ./mongo-volume:/data/db
  ports:
  - "27017:27017" # specify port forwarding

 administration: # name of the third service
  image: mongo-express
  container_name: my-mongo-gui-container
  environment:
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_SERVER=database
    - ME_CONFIG_MONGODB_AUTH_DATABASE=db
    - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=pass
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
  depends_on:
    - database
  ports:
    - "8081:8081"